#!/bin/bash

# Copied from official Docker httpd image
# https://github.com/docker-library/httpd
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND
